# Generated by Django 4.2.7 on 2026-01-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_trend_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
