# Generated by Django 4.2.7 on 2026-01-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_last_trend_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_trend_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
