# Generated by Django 4.2.7 on 2026-02-02 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_notification_updated_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='airecommendation',
            name='unique_pending_recommendation',
        ),
        migrations.AlterUniqueTogether(
            name='airecommendation',
            unique_together={('product', 'recommendation_type', 'status')},
        ),
    ]
