# Generated by Django 4.2.7 on 2026-02-04 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0007_remove_airecommendation_unique_pending_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderqueue',
            name='message_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderqueue',
            name='message_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderqueue',
            name='message_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderqueue',
            name='order_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderqueue',
            name='ordered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
