# Generated by Django 4.2.7 on 2026-02-09 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0010_salesbill_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderqueue',
            name='approved_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderqueue',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_requests', to='inventory.salesbill'),
        ),
        migrations.AddField(
            model_name='orderqueue',
            name='bill_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderqueue',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderqueue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('received', 'Received'), ('approved', 'Approved by Admin'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
