# Generated by Django 4.2.7 on 2026-02-09 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0011_orderqueue_approved_quantity_orderqueue_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expirystock',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
