# Generated by Django 4.2.27 on 2026-02-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_shopowner_restockorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbill',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesbill',
            name='verification_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
